# Generated by Django 6.0 on 2026-05-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=258)),
                ('level', models.CharField(max_length=258)),
                ('branch', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('senior', 'Senior'), ('normal', 'Normal')], default='normal', max_length=68)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Teachers', to='data.province')),
            ],
        ),
    ]
