# Generated by Django 6.0 on 2026-07-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('data', '0003_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Teachers', to='data.city'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='agents_avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
