# Generated by Django 6.0 on 2026-07-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_teacher_city_teacher_image_teacher_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
    ]
