# Generated by Django 6.0 on 2026-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.SmallIntegerField(default=0),
        ),
    ]
