# Generated by Django 6.0 on 2026-07-16 10:47

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalenge', '0005_challengeregistration'),
        ('courses', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='capasity',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='course',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='chalenge.agegroup'),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=django_jalali.db.models.jDateField(default='1400-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=django_jalali.db.models.jDateField(default='1400-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='explain',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=django_jalali.db.models.jDateField(default='1400-12-12'),
            preserve_default=False,
        ),
    ]
