# Generated by Django 6.0 on 2026-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_capasity_course_capacity_course_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='public'),
            preserve_default=False,
        ),
    ]
