# Generated by Django 6.0 on 2026-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_email_alter_profile_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chalenge_participated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='jurisprudence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='technical_workshops',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
