# Generated by Django 6.0 on 2026-05-17 17:45

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_chalenge_participated_profile_jurisprudence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('level', models.CharField(max_length=68)),
                ('branch', models.CharField(max_length=68)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('deadline', django_jalali.db.models.jDateField()),
            ],
        ),
    ]
