# Generated by Django 6.0 on 2026-05-17 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='national_code',
        ),
        migrations.AddField(
            model_name='membership',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
