# Generated by Django 6.0 on 2026-05-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_membership_branch_remove_membership_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='level',
        ),
    ]
