# Generated by Django 6.0 on 2026-05-21 16:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_membership_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='sport_insurance_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_path),
        ),
    ]
