# Generated by Django 6.0 on 2026-07-01 16:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_birth_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_certificate_serial',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_maried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='issue_place',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'اقا'), ('female', 'خانم')], max_length=10),
        ),
    ]
