# Generated by Django 6.0 on 2026-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name_latin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
