# Generated by Django 6.0 on 2026-05-10 16:53

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalenge',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='chalenge',
            name='deadline',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='chalenge',
            name='gender',
            field=models.CharField(choices=[('male', 'اقایان'), ('female', 'بانوان')]),
        ),
    ]
