# Generated by Django 6.0 on 2026-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalenge', '0002_alter_chalenge_date_alter_chalenge_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=68)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='chalenge',
            name='image',
            field=models.ImageField(default='', upload_to='chalenges/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chalenge',
            name='level',
            field=models.CharField(choices=[('country', 'کشوری'), ('provincial', 'استانی'), ('regional', 'منطقه ای')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chalenge',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='chalenge',
            name='age_groups',
            field=models.ManyToManyField(to='chalenge.agegroup'),
        ),
        migrations.AddField(
            model_name='chalenge',
            name='weight_categories',
            field=models.ManyToManyField(blank=True, null=True, to='chalenge.weightcategory'),
        ),
    ]
