# Generated by Django 6.0 on 2026-07-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalenge', '0003_agegroup_weightcategory_chalenge_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chalenges/'),
        ),
    ]
