# Generated by Django 6.0 on 2026-07-10 09:07

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalenge', '0004_alter_chalenge_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('chalenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chalenge.chalenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chalenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'chalenge'), name='unique_user_challenge')],
            },
        ),
    ]
