# Generated by Django 6.0 on 2025-12-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
