# Generated by Django 6.0 on 2026-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
    ]
