# Generated by Django 6.0 on 2026-05-10 19:08

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default='1404-09-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=68),
        ),
    ]
